# Generated by Django 2.1.5 on 2019-02-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='checklist',
            field=models.ManyToManyField(blank=True, null=True, to='todo.Checklist'),
        ),
    ]
